server:
  port: 8020

spring:
  application:
    name: delivery-service
  cloud:
    stream:
      function:
        definition: handleOrder
        bindings:
          handleOrder-in-0: order-service
      bindings:
        order-service:
          destination: order-service
#      rabbit:
#        bindings:
#          output:
#            consumer:
#              declare-exchange: false